easy_admin:
  #site_name: ProjectCars

  #design:
  #  menu:
 #     - { route: 'homepage', label: 'Back to the website', icon: 'home' }

  entities:
    User:
      class: App\Entity\User
      list:
        fields:
          - name 
          - password
          - { property: 'email', type: 'email' }
          - { property: 'creationDate', type: 'datetime',type_options: { disabled: true } }
      edit:
        fields:
          - name 
          - password 
          - profilePicturePath
          - { property: 'email', type: 'email' }
          - { property: 'creationDate', type: datetime, type_options: { disabled: true }}  
      
    Car:    
      class: App\Entity\Car
      list:
        fields:
          - slug
          - id
          - owner
          - brand
          - model
          - year
          - capacity
          - power
          - torque
          - drivetrain
          - fuel
#          - description
#          - engineDescription
#          - externalDescription
#          - internalDescription
          - { property: 'creationDate', type: 'datetime' }
          
      edit:
        fields:
          - slug
          - 'brand'
          - 'model'
          - 'year'
          - 'capacity'
          - 'power'
          - 'torque'
          - 'drivetrain'
          - 'fuel'
          - 'description'
          - 'engineDescription'
          - 'externalDescription'
          - 'internalDescription'

          
#          - 'owner'
#          - { property: 'creationDate', type: 'datetime', type_options: { disabled: true }} 
              

    Country:  
      class: App\Entity\Country
      list:   
        fields:
           - name
      edit:
        fields:
          - 'name'

    Brand:  
      class: App\Entity\Brand
      list:
        fields:
          - name
          - country
      edit:
        fields:
           - 'name'
           - 'country'

    Drivetrain:  
      class: App\Entity\Drivetrain
      list:
        fields:
          - type
      edit:
        fields:
          - 'type'

    Fuel:  
      class: App\Entity\Fuel
      list:
        fields:
          - type
      edit:
        fields:
          - 'type'
    
    Picture:  
      class: App\Entity\Picture
      list:
        fields:
          - path
          - car
      edit:
        fields:
          - 'path'
          - 'car'

    Comment:  
      class: App\Entity\Comment
      list:
        fields:
          - content
          - author
          - creationDate
          - carPost
      edit:
        fields:
          - 'content'
          - 'author'
          - 'carPost'

  
